site_name: Apuntes 2º ASIR
site_description: Documentación y prácticas de administración de sistemas
site_author: Eduardo Elias

theme:
  name: material
  language: es

  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro

    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.prune
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list

nav:
  - Inicio: index.md

  - Administración de Sistemas Operativos: aso/00-index.md

  - Análisis y Gestión de Bases de Datos: agbd/00-index.md

  - Seguridad y Alta Disponibilidad: sad/00-index.md

  - Servicios de Red e Internet: sri/00-index.md

  - Implantación de Aplicaciones Web: iaw/00-index.md

  - Digitalización aplicada a los sectores productivos: dsp/00-index.md

  - Sostenibilidad aplicada al sistema productivo: ssp/00-index.md

  - Inglés técnico: ingles/00-index.md

  - MPO: mpo/00-index.md